In [39]:
import gymnasium as gym
import numpy as np
import time

In [40]:
env = gym.make('CartPole-v1', render_mode='human')

In [30]:
(state, _) = env.reset()
env.step(0)

D:\anaconda3\envs\DL\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(array([ 3.1479817e-02, -1.6105480e-01,  1.0753754e-04,  2.6175240e-01],
       dtype=float32),
 1.0,
 False,
 False,
 {})

In [21]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [22]:
env.observation_space.high

array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)

In [23]:
env.observation_space.low

array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32)

In [24]:
env.action_space

Discrete(2)

In [25]:
env.spec

EnvSpec(id='CartPole-v1', entry_point='gym.envs.classic_control.cartpole:CartPoleEnv', reward_threshold=475.0, nondeterministic=False, max_episode_steps=500, order_enforce=True, autoreset=False, disable_env_checker=False, apply_api_compatibility=False, kwargs={'render_mode': 'human'}, namespace=None, name='CartPole', version=1)

In [43]:
nEpisode = 5
timeSteps = 100

for episodeIndex in range(nEpisode):
    initial_state = env.reset()
    print(episodeIndex)
    env.render()
    observationsList = []
    for timeIndex in range(timeSteps):
        print(timeIndex)
        randomAction= env.action_space.sample()
        observations, reward, terminated, truncated, info = env.step(randomAction)
        observationsList.append(observations)
        time.sleep(0.1)
        if terminated:
            time.sleep(1)
            break
env.close()

error: display Surface quit

In [42]:
env.close()