In [73]:
import numpy as np
import gym
import random
from tqdm import tqdm
from pyvirtualdisplay import Display
import imageio

In [74]:
env = gym.make("FrozenLake-v1", map_name="4x4", is_slippery=False)

In [75]:
print("Obervation Space: ", env.observation_space)
print("Sample observation ", env.observation_space.sample())

Obervation Space:  Discrete(16)
Sample observation  9


In [76]:
print("Action Space: ", env.action_space.n)
print("Action Space Sample: ", env.action_space.sample())

Action Space:  4
Action Space Sample:  2


In [77]:
state_space = env.observation_space.n
action_space = env.action_space.n

In [78]:
def init_Q_Table(state, action):
    Q_Table = np.zeros((state, action))
    return Q_Table


QTable = init_Q_Table(state_space, action_space)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Epsilon Greedy policy used for choose action
### where, the greedy policy used to update the policy

In [79]:
def epsilon_greedy_policy(QTable, state, epsilon):
    random_int = random.uniform(0, 1)
    if random_int > epsilon:
        action = np.argmax(QTable[state])
    else:
        action = env.action_space.n
    return action

In [80]:
def greedy_policy(Qtable, state):
    action = np.argmax(Qtable[state])
    return action

  0%|          | 0/10000 [00:00<?, ?it/s]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
n_episode = 1000
learning_rate = 0.7

n_eval_episode = 100

max_steps = 99
gamma = 0.95
eval_seed = []

# Exploration parameters
max_epsilon = 1.0
min_epsilon = 0.05
decay_rate = 0.0005


def training(n_episode, min_epsilon, max_epsilon, decay_rate, env, max_steps, Qtable):
    for episode in trange(n_episode):
        epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)
        state = env.reset()
        step = 0
        done=False
        
        for step in range(max_steps):
            action = epsilon_greedy_policy(QTable, state, epsilon)
            
            new_state, reward, done, info = env.step(action)
            
            Qtable[state][action]= Qtable[state][action] + learning_rate*(reward+gamma*np.argmax(Qtable[state])- Qtable[state][action])
        
        if done:
            break
        
            state = new_state
        
        return  Qtable




In [ ]:
Qtable_frozenlake = training(n_episode, min_epsilon, max_epsilon, decay_rate, env, max_steps, QTable)