In [1]:
import numpy as np

In [ ]:
env_rows = 11
env_columns = 11
q_values = np.zeros((env_rows, env_columns, 4))

#### define Actions as up = 0, right = 1, down = 2, left = 3

In [5]:
actions = ['up', 'right','down', 'left']


In [53]:
rewards = np.full((env_rows, env_columns), -100.)
rewards[0, 5]=100.

aisles = {}
aisles[1]=[i for i in range(1, 10)]
aisles[2]=[1,7,9]
aisles[3]=[i for i in range(1, 8)]
aisles[3].append(9)
aisles[4]=[3,7]
aisles[5]=[i for i in range(11)]
aisles[6]=[5]
aisles[7]=[i for i in range(1, 10)]
aisles[8]=[3,7]
aisles[9]=[i for i in range(11)]

for row_index in range(1, 10):
    for colurewardsmn_index in aisles[row_index]:
        rewards[row_index, column_index] = -1.
for row in rewards:
    print(row)


[-100. -100. -100. -100. -100.  100. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100.   -1. -100. -100. -100. -100. -100.   -1. -100.   -1. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.   -1. -100.]
[-100. -100. -100.   -1. -100. -100. -100.   -1. -100. -100. -100.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-100. -100. -100. -100. -100.   -1. -100. -100. -100. -100. -100.]
[-100.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1. -100.]
[-100. -100. -100.   -1. -100. -100. -100.   -1. -100. -100. -100.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[-100. -100. -100. -100. -100. -100. -100. -100. -100. -100. -100.]


In [54]:
def is_terminal_state(current_row_index, current_col_index):
    if rewards[current_row_index, current_col_index]== -1.:
        return False
    else:
        return True

In [24]:
def get_starting_location():
    current_row_index= np.random.randint(env_rows)
    current_col_index = np.random.randint(env_columns)
    while is_terminal_state(current_row_index, current_col_index):
        current_row_index= np.random.randint(env_rows)
        current_col_index = np.random.randint(env_columns)
    return current_row_index, current_col_index

In [20]:
def get_next_action(column_row_index, column_col_index, epsilon):
    if np.random.random() < epsilon:
        return np.argmax(q_values[column_row_index, column_col_index])
    else:
        return np.random.randint(4)

In [26]:
def get_next_location(current_row_index, current_col_index, action_index):
    new_row_index = current_row_index
    new_col_index = current_col_index

    if actions[action_index] == 'up' and current_row_index > 0:
        new_row_index -=1
    elif actions[action_index] == 'right' and current_col_index < env_columns -1:
        new_col_index +=1
    elif actions[action_index] == 'down' and current_row_index < env_rows -1:
        new_row_index +=1
    elif actions[action_index] == 'left' and current_col_index > 0:
        new_col_index -=1
    return new_row_index, new_col_index

In [46]:
def get_shortest_path(start_row_index, start_col_index):
    if is_terminal_state(start_row_index, start_col_index):
        return []
    else:
        current_row_index, current_col_index = start_row_index, start_col_index
        shortest_path = []
        shortest_path.append([current_col_index, current_col_index])

        while not is_terminal_state(start_row_index, start_col_index):
            action_index = get_next_action(current_col_index, current_col_index, 1.)
            current_row_index, current_col_index = get_next_location(current_row_index, current_col_index, action_index)
            shortest_path.append([current_row_index, current_col_index])
    return shortest_path

            

In [49]:
epsilon = 0.9
discount_factor = 0.9
learning_rate = 0.9

for episode in range(1000):
    row_index, column_index = get_starting_location()

    while not is_terminal_state (row_index, column_index):
        action_index = get_next_action(row_index, column_index, epsilon)

        old_row_index, old_col_index = row_index, column_index
        row_index, column_index = get_next_location(row_index, column_index, action_index)
        reword = rewards[row_index, column_index]
        old_q_value = q_values[old_row_index, old_col_index, action_index]
        temporal_different = reword + (discount_factor* np.max(q_values[row_index, column_index])) - old_q_value

        new_q_value = old_q_value + (learning_rate * temporal_different)
        q_values[old_row_index, old_col_index, action_index] = new_q_value
    print("episode: ", episode)
print("Training Completed")

episode:  0
episode:  1
episode:  2
episode:  3
episode:  4
episode:  5
episode:  6
episode:  7
episode:  8
episode:  9
episode:  10
episode:  11
episode:  12
episode:  13
episode:  14
episode:  15
episode:  16
episode:  17
episode:  18
episode:  19
episode:  20
episode:  21
episode:  22
episode:  23
episode:  24
episode:  25
episode:  26
episode:  27
episode:  28
episode:  29
episode:  30
episode:  31
episode:  32
episode:  33
episode:  34
episode:  35
episode:  36
episode:  37
episode:  38
episode:  39
episode:  40
episode:  41
episode:  42
episode:  43
episode:  44
episode:  45
episode:  46
episode:  47
episode:  48
episode:  49
episode:  50
episode:  51
episode:  52
episode:  53
episode:  54
episode:  55
episode:  56
episode:  57
episode:  58
episode:  59
episode:  60
episode:  61
episode:  62
episode:  63
episode:  64
episode:  65
episode:  66
episode:  67
episode:  68
episode:  69
episode:  70
episode:  71
episode:  72
episode:  73
episode:  74
episode:  75
episode:  76
episode: 

In [50]:
print(get_shortest_path(3,9))

KeyboardInterrupt: 